# Configuración de Bandit para análisis de seguridad
exclude_dirs:
  - tests
  - test
  - __pycache__
  - .git
  - .venv
  - venv
  - env

skips:
  - B101  # Skip assert_used test
  - B601  # Skip paramiko calls

severity: medium
confidence: medium

# Reglas específicas para Flask
tests:
  - B201  # flask_debug_true
  - B301  # pickle
  - B302  # marshal
  - B303  # md5
  - B304  # cipher
  - B305  # cipher_mode
  - B306  # mktemp_q
  - B307  # eval
  - B308  # mark_safe
  - B309  # httpsconnection
  - B310  # urllib_urlopen
  - B311  # random
  - B312  # telnetlib
  - B313  # xml_bad_cElementTree
  - B314  # xml_bad_ElementTree
  - B315  # xml_bad_expatreader
  - B316  # xml_bad_expatbuilder
  - B317  # xml_bad_sax
  - B318  # xml_bad_minidom
  - B319  # xml_bad_pulldom
  - B320  # xml_bad_etree
  - B321  # ftplib
  - B322  # input
  - B323  # unverified_context
  - B324  # hashlib_new_insecure_functions
  - B325  # tempnam
